config sonarcloud and main-branch-pipeline

diff --git a/.github/workflows/mail-branch-pipeline.yml b/.github/workflows/mail-branch-pipeline.yml
--- a/.github/workflows/mail-branch-pipeline.yml
+++ b/.github/workflows/mail-branch-pipeline.yml
@@ -13,10 +13,11 @@ jobs:
     steps:
       - name: Check environment variables
         run: |
-          echo "DATASOURCE_HOST=${{ secrets.DATASOURCE_HOST }}"
-          echo "DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}"
-          echo "DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}"
-          echo "DATASOURCE_DATABASE=${{ secrets.DATASOURCE_DATABASE }}"
+          echo "RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }}"
+          echo "RDS_PORT=${{ secrets.RDS_PORT }}"
+          echo "RDS_DATABASE=${{ secrets.RDS_DATABASE }}"
+          echo "RDS_USERNAME=${{ secrets.RDS_USERNAME }}"
+          echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}"
           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
           echo "APP_PORT=${{ secrets.APP_PORT }}"
           echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
@@ -50,63 +51,51 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  setup:
-    name: Setup | Neon workflow
+  configure_aws:
+    name: Configure AWS Credentials
     runs-on: ubuntu-latest
     needs: validate-env
-    if: success()
-    outputs:
-      branch: ${{ steps.branch_name.outputs.current_branch }}
     steps:
-      - name: Get Branch Name
-        id: branch_name
-        uses: tj-actions/branch-names@v8
-
-  deploy_to_neon:
-    name: Deploy to Neon Using Deployment Branch
-    needs: setup
-    if: success()
-    runs-on: ubuntu-latest
-    steps:
-      # STEP-1: Create a new Branch for deployment
-      - name: Use Neon Deployment Branch
-        id: use_neon_branch
-        uses: neondatabase/create-branch-action@v5
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          project_id: ${{ secrets.NEON_PROJECT_ID }}
-          username: "Tasks_owner"
-          parent: main
-          database: Tasks
-          branch_name: Task-deployment # <-------------------- Add the branch name to be created
-          api_key: ${{ secrets.NEON_API_KEY }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: your-aws-region # e.g., us-east-1
 
-      # STEP-2: Run Migration
-      - name: Check Database Connection and Run Migration
-        run: |
-          # Check if DATABASE_URL is set
-          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
-            echo "DATABASE_URL is not set. Cannot proceed with migration."
-            exit 1
-          fi
+  deploy_to_rds:
+    name: Deploy to AWS RDS
+    runs-on: ubuntu-latest
+    needs: [validate-env, configure_aws, sonarcloud]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-          # Test if the database is reachable
-          PGPASSWORD=$(echo "${{ secrets.DATABASE_URL }}" | sed -n 's/.*:\/\/*:\([^@]*\).*/\1/p') \
-          psql $(echo "${{ secrets.DATABASE_URL }}" | sed -n 's/\(.*@\)\(.*\)\/.*/\2/p') -c '\q'
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16" # Specify your Node.js version
 
-          if [ $? -ne 0 ]; then
-            echo "Cannot connect to the database. Please check the connection settings."
-            exit 1
-          fi
+      - name: Install dependencies
+        run: yarn install
 
-          # Run the migration if everything is okay
-          yarn run db:migrate
+      - name: Run Database Migrations
         env:
-          DATABASE_URL: "${{ secrets.DATABASE_URL }}"
+          DATABASE_URL: "postgresql://${{ secrets.RDS_USERNAME }}:${{ secrets.RDS_PASSWORD }}@${{ secrets.RDS_ENDPOINT }}:${{ secrets.RDS_PORT }}/${{ secrets.RDS_DATABASE }}"
+        run: |
+          # Test database connection
+          PGPASSWORD=${{ secrets.RDS_PASSWORD }} psql -h ${{ secrets.RDS_ENDPOINT }} -p ${{ secrets.RDS_PORT }} -U ${{ secrets.RDS_USERNAME }} -d ${{ secrets.RDS_DATABASE }} -c '\q'
+          if [ $? -ne 0 ]; then
+            echo "Cannot connect to the AWS RDS database. Please check the connection settings."
+            exit 1
+          fi
 
-  # STEP-3: if no error on Migration Ok then Deploy to vercel
+          # Run the migration
+          yarn run db:migrate
+
   deploy_to_vercel:
     name: Deploy to Vercel
-    needs: deploy_to_neon
+    needs: deploy_to_rds
     if: success()
     runs-on: ubuntu-latest
     steps:
@@ -139,17 +128,3 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs
-
-  delete_neon_branch:
-    # STEP-5: Wait for the end of the process and clean up regardless of success or failure
-    name: Delete Neon Deployment Branch
-    runs-on: ubuntu-latest
-    needs: [deploy_to_neon, deploy_to_vercel, build] # Depends on previous jobs
-    if: always() # Run regardless of success or failure
-    steps:
-      - name: Delete Neon Deployment Branch
-        uses: neondatabase/delete-branch-action@v3
-        with:
-          api_key: ${{ secrets.NEON_API_KEY }}
-          project_id: ${{ secrets.NEON_PROJECT_ID }}
-          branch_name: Task-deployment # <-------------------- Add the branch name to be deleted
